# Generated by Django 5.2.14 on 2026-06-02 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='会话标题')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('message_count', models.IntegerField(default=0, verbose_name='消息数')),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='documents.collection', verbose_name='关联集合')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rag_sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '会话',
                'verbose_name_plural': '会话',
                'db_table': 'sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('query', models.TextField(verbose_name='用户查询')),
                ('answer', models.TextField(verbose_name='系统回答')),
                ('query_class', models.CharField(max_length=50, verbose_name='查询类型')),
                ('class_scores', models.JSONField(default=dict, verbose_name='分类分数')),
                ('channel_weights', models.JSONField(default=list, verbose_name='通道权重')),
                ('sources', models.JSONField(default=list, verbose_name='来源文档')),
                ('latency', models.FloatField(default=0.0, verbose_name='响应时间(秒)')),
                ('is_cached', models.BooleanField(default=False, verbose_name='是否命中缓存')),
                ('feedback', models.CharField(blank=True, choices=[('good', '好'), ('bad', '差'), (None, '未评价')], max_length=20, null=True, verbose_name='用户反馈')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.session', verbose_name='所属会话')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
    ]
