# Generated by Django 5.2.14 on 2026-06-02 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('query', models.TextField(verbose_name='查询内容')),
                ('expected_answer', models.TextField(verbose_name='期望回答')),
                ('actual_answer', models.TextField(blank=True, verbose_name='实际回答')),
                ('query_class', models.CharField(max_length=50, verbose_name='查询类型')),
                ('suggested_weights', models.JSONField(default=list, verbose_name='建议权重')),
                ('current_weights', models.JSONField(default=list, verbose_name='当前权重')),
                ('status', models.CharField(choices=[('active', '活跃'), ('resolved', '已解决'), ('ignored', '已忽略')], default='active', max_length=20, verbose_name='状态')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='解决备注')),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bad_cases', to='documents.collection', verbose_name='关联集合')),
            ],
            options={
                'verbose_name': 'Bad Case',
                'verbose_name_plural': 'Bad Cases',
                'db_table': 'bad_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('query', models.TextField(verbose_name='查询内容')),
                ('query_class', models.CharField(max_length=50, verbose_name='查询类型')),
                ('response_time', models.FloatField(verbose_name='响应时间(秒)')),
                ('cache_hit', models.BooleanField(default=False, verbose_name='缓存命中')),
                ('result_count', models.IntegerField(default=0, verbose_name='结果数量')),
                ('error', models.TextField(blank=True, verbose_name='错误信息')),
            ],
            options={
                'verbose_name': '查询日志',
                'verbose_name_plural': '查询日志',
                'db_table': 'query_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['query_class', 'created_at'], name='query_logs_query_c_8852a0_idx'), models.Index(fields=['-response_time'], name='query_logs_respons_4a6238_idx')],
            },
        ),
        migrations.CreateModel(
            name='RetrievalMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('date', models.DateField(verbose_name='日期')),
                ('total_queries', models.IntegerField(default=0, verbose_name='总查询数')),
                ('avg_response_time', models.FloatField(default=0.0, verbose_name='平均响应时间')),
                ('cache_hit_rate', models.FloatField(default=0.0, verbose_name='缓存命中率')),
                ('keyword_queries', models.IntegerField(default=0, verbose_name='关键词查询数')),
                ('semantic_queries', models.IntegerField(default=0, verbose_name='语义查询数')),
                ('balanced_queries', models.IntegerField(default=0, verbose_name='平衡查询数')),
            ],
            options={
                'verbose_name': '检索指标',
                'verbose_name_plural': '检索指标',
                'db_table': 'retrieval_metrics',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
    ]
