# Generated by Django 5.2.14 on 2026-06-02 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='集合名称')),
                ('description', models.TextField(blank=True, verbose_name='集合描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '文档集合',
                'verbose_name_plural': '文档集合',
                'db_table': 'collections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('title', models.CharField(max_length=500, verbose_name='文档标题')),
                ('file_path', models.CharField(max_length=1000, verbose_name='文件路径')),
                ('file_type', models.CharField(max_length=50, verbose_name='文件类型')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小(字节)')),
                ('total_chunks', models.IntegerField(default=0, verbose_name='总块数')),
                ('processed_chunks', models.IntegerField(default=0, verbose_name='已处理块数')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.collection', verbose_name='所属集合')),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '文档',
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.TextField(verbose_name='内容')),
                ('chunk_index', models.IntegerField(verbose_name='块索引')),
                ('vector_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='向量ID')),
                ('metadata', models.JSONField(default=dict, verbose_name='元数据')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document', verbose_name='所属文档')),
            ],
            options={
                'verbose_name': '文档块',
                'verbose_name_plural': '文档块',
                'db_table': 'chunks',
                'ordering': ['chunk_index'],
                'indexes': [models.Index(fields=['document', 'chunk_index'], name='chunks_documen_a11b61_idx')],
            },
        ),
    ]
